### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by darkhog** [fstxz/prop_placer#1]
````
  res://addons/prop_placer/gui_handler.gd:52 - Parse Error: Static function "popup_node_selector()" not found in base "GDScriptNativeClass".
  res://addons/prop_placer/plugin.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/prop_placer/plugin.gd" with error "Compilation failed". (User)
  res://addons/prop_placer/plugin.gd:42 - Invalid set index 'prop_placer_instance' (on base: 'Control (gui_handler.gd)') with value of type 'EditorPlugin (plugin.gd)'.
````

**Comment by fstxz** [comment]
Are you on Godot 4.3? popup_node_selector() is only available in Godot 4.3.

edit: I was using Godot 4.3 dev 5 while developing the plugin. You can download it from [here](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-5/#downloads) and try again.

**Comment by HPlatinum** [comment]
I was getting the same error with 4.3 Dev 1. Swapped to Dev 5 (.Net) and got this error:

**Comment by fstxz** [comment]
The plugin is now compatible with Godot 4.2. If you are using Godot 4.2, make sure to reload the editor after installing the plugin.
