### ISSUE TITLE
node names

### ISSUE THREAD

**Issue by ianmckenna87** [fstxz/prop_placer#11]
plug-in works very nicely, the instanced nodes are given assigned names by Godot and don't maintain their scene names, if that was something that could be fixed?

![image](https://github.com/user-attachments/assets/84965e62-670b-4f8a-b77c-7ce5e702a03e)

**Comment by fstxz** [comment]
From Godot's docs:

> If force_readable_name is true, improves the readability of the added node. If not named, the node is renamed to its type, and if it shares [name](https://docs.godotengine.org/en/4.3/classes/class_node.html#class-node-property-name) with a sibling, a number is suffixed more appropriately. __This operation is very slow. As such, it is recommended leaving this to false, which assigns a dummy name featuring @ in both situations__.

I can force readable names, but this should probably be an option. Thanks for the suggestion!

**Comment by ianmckenna87** [comment]
> From Godot's docs:
> 
> > If force_readable_name is true, improves the readability of the added node. If not named, the node is renamed to its type, and if it shares [name](https://docs.godotengine.org/en/4.3/classes/class_node.html#class-node-property-name) with a sibling, a number is suffixed more appropriately. **This operation is very slow. As such, it is recommended leaving this to false, which assigns a dummy name featuring @ in both situations**.
> 
> I can force readable names, but this should probably be an option. Thanks for the suggestion!

I'm wondering if the performance hit is as much a concern in the editor for building a level as at run time in a running game? If that were the case it might be better to include it as a performance option for situations with a very heavy scene tree. Just my thoughts!

**Comment by fstxz** [comment]
I think I will enable readable names by default and add an option to
disable it if it causes performance issues
