### ISSUE TITLE
Increase the default size of the collection creation and import windows

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#2]
The size of the file dialogs for creating new collections and importing them is just way too small:
![grafik](https://github.com/fstxz/prop_placer/assets/161153520/b5657e2e-c21f-4f0b-b6f1-5bce9b8094ae)
This can be very quickly and easily solved by going into the gui_handler.gd script and adding two small lines to adjust the default size of these windows:
![grafik](https://github.com/fstxz/prop_placer/assets/161153520/d28f9234-a9cd-405f-a693-40a63936b66d)
This results in windows which have a much more reasonable size:
![grafik](https://github.com/fstxz/prop_placer/assets/161153520/a3b0295c-b7fe-4c96-a774-98749251ad21)

**Comment by fstxz** [comment]
Thanks for reporting! Fixed. 638666699a2ea18754b00d6ce54cfc22fd51c98c
