### ISSUE TITLE
Self-collision issue with the object being placed

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#3]
When deactivating the grid option, and the object one is about to place is a PhysicsBody or has a collision object inside of it, the raycast which is used for determening the position of the mouse cursor detects the preview object and tries to adjust its position. This results in the preview object moving closer to the camera repeatedly, after which snapping back to the actual scene geometry. This is best explained by having a look here:
[Bildschirmaufzeichnung vom 2024-05-09, 02-33-36.webm](https://github.com/fstxz/prop_placer/assets/161153520/458e93e6-b0a9-4006-9352-bb154b7940ad)
The raycast detects the goal as a collision object, even thouhgh it should simply be a preview object without collision before placing.

**Comment by fstxz** [comment]
Thanks for reporting again. This is now fixed (hopefully).

**Comment by fstxz** [comment]
> even thouhgh it should simply be a preview object without collision before placing.

This is because preview object is the whole scene, including objects that are not meshes, e.g. particles, lights, etc.
