### ISSUE TITLE
Error whenever opening a property in the inspector

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#4]
Whenever I click on a property in the inspector (for example a material or a color gradient) it doesn't open the menu for editing the property, but it throws an error saying this
`Condition "plugins_list.has(p_plugin)" is true.`
This issue can be observed here, where I try to edit the gradient color of a GPUParticle3D Node:
[inspector_broken.webm](https://github.com/fstxz/prop_placer/assets/161153520/ddb8ec1d-f947-493a-8690-21990a398578)
I disabled all other plugins I have and it turned out that it is indeed this one which is causing the problem. Unfortunately, I don't have any idea on why this might be happening. I ran Godot using the terminal and got this output for opening the ParticleProcessMaterial and the GradientTexture:
```
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:7568)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:7568)
```
This seems to occur for all resources which are inside of another resource (in this case GradientTexture1D in ParticleProcessMaterial).

**Comment by fstxz** [comment]
I will look into it. I noticed that too, but I thought that was a problem with the dev version of Godot. And the error message doesn't help sadly. As a workaround, you can right click on the resource and click "Edit".

**Comment by fstxz** [comment]
Thanks for reporting, fixed.
