### ISSUE TITLE
Add option to change grid layer shortcuts

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#5]
The new grid visuals and functionality work great so far! One odd thing however I think are the keyboard shortcuts. Your mouse movement system is good and it works well, but I feel that the option of using the GridMap controls (Ctrl + mouse_wheel_up / Ctrl + mouse_wheel_down) would be really nice. This would serve new users of your plugin to understand the controls directly, and then later on maybe switch to the ones you provide right now.

**Comment by fstxz** [comment]
Seems reasonable, I will change it.

**Comment by fstxz** [comment]
Done.
