### ISSUE TITLE
Add option to randomly rotate on local Y axis

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#8]
It would be useful to have the option to randomly rotate the object on the local Y axis (rotating around the up vector of the surface below). This would have practical application in foliage- and Decal-placement, as it would result in more organically placed objects due to the randomness. Here a visual of what I mean by this exactly
![rotation_graphic](https://github.com/fstxz/scene_tools/assets/161153520/8bbb7eff-a185-418c-8496-637195e8eba4)
After each placed object, the rotation should be randomized. In addition, it might also be useful to give the user the option to randomly rotate again when clicking the right mouse button while this random rotation mode is enabled. This way, if the randomized rotation is too similar to the objects placed around it, the user can quickly generate a new random rotation for the object being placed.

**Comment by fstxz** [comment]
Yes, this is planned.

**Comment by fstxz** [comment]
Done, but currently without an option to randomize again.

**Comment by Smorty10** [comment]
Then I will close the issue
