### ISSUE TITLE
[FEATURE] Add optimization with Multimesh

### ISSUE THREAD

**Issue by Smorty10** [fstxz/prop_placer#9]
This is somewhat of a larger feature request, but having the option to optimize mesh drawing by automatically combining meshes of the same kind would be amazing. Allowing this for all scenes which have a MeshInstance as the root makes a lot of sense in my opinion. Placing foliage like bushes and random wooden logs on the ground using this tool would become loads more drawcall-efficient.

**Comment by fstxz** [comment]
Yeah, I'd like to have something like this. Need to think about how to properly implement it and integrate with existing features and in UI.

**Comment by Smorty10** [comment]
I think I kinda fixed this myself by writing my own plugin... It does exactly this: Combining multiple MeshInstances to one MultiMesh. That can act as something of a post-processing step after designing the entire scene so it probably doesn't make sense to implement this into this plugin.

**Comment by Smorty10** [comment]
I might aswell link it here so people can have a look at it if they need it
https://gitlab.com/Marty_Friedrich/optiscene
